/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Weapon/fps_animated_carbine.glb
Author: DJMaesen (https://sketchfab.com/bumstrum)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fps-animated-carbine-62977bb4c53047a185b9f3a0cdf56b87
Title: fps animated carbine
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ModelFPS(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/Weapon/fps_animated_carbine.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
          <group name="483e341a4f714edfbbeda411d6b11187fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="carbine" position={[0, 5.28, -0.14]}>
                  <group name="lid" position={[-1.67, 8.84, 14.1]}>
                    <mesh name="lid_carbine_0" geometry={nodes.lid_carbine_0.geometry} material={materials.carbine} />
                  </group>
                  <group name="handle" position={[0, 13.02, -1.39]}>
                    <group name="handle2" position={[2.05, 0, -0.82]}>
                      <mesh name="handle2_carbine_0" geometry={nodes.handle2_carbine_0.geometry} material={materials.carbine} />
                    </group>
                    <mesh name="handle_carbine_0" geometry={nodes.handle_carbine_0.geometry} material={materials.carbine} />
                  </group>
                  <group name="bolt" position={[0, 10.01, 14]}>
                    <mesh name="bolt_carbine_0" geometry={nodes.bolt_carbine_0.geometry} material={materials.carbine} />
                  </group>
                  <group name="boltcatch" position={[-1.51, 9.54, 3.18]} rotation={[0, 0.34, 0]}>
                    <mesh name="boltcatch_carbine_0" geometry={nodes.boltcatch_carbine_0.geometry} material={materials.carbine} />
                  </group>
                  <group name="release" position={[1.69, 7.38, 10.28]}>
                    <mesh name="release_carbine_0" geometry={nodes.release_carbine_0.geometry} material={materials.carbine} />
                  </group>
                  <group name="clip" position={[0, 0.12, 14.88]}>
                    <group name="bullet" position={[0, 7.51, -0.12]}>
                      <mesh name="bullet_carbine_0" geometry={nodes.bullet_carbine_0.geometry} material={materials.carbine} />
                    </group>
                    <mesh name="clip_carbine_0" geometry={nodes.clip_carbine_0.geometry} material={materials.carbine} />
                  </group>
                  <group name="trigger" position={[0, 5.47, 6.06]}>
                    <mesh name="trigger_carbine_0" geometry={nodes.trigger_carbine_0.geometry} material={materials.carbine} />
                  </group>
                  <group name="base" position={[0, 0.92, 0.59]}>
                    <mesh name="base_carbine_0" geometry={nodes.base_carbine_0.geometry} material={materials.carbine} />
                  </group>
                  <group name="scope" position={[0, 13.24, 6.56]}>
                    <group name="lens" position={[0, 3.58, -1.65]}>
                      <mesh name="lens_lens_0" geometry={nodes.lens_lens_0.geometry} material={materials.lens} />
                    </group>
                    <mesh name="scope_carbine_0" geometry={nodes.scope_carbine_0.geometry} material={materials.carbine} />
                  </group>
                </group>
                <group name="L_arm_Pole" position={[24.21, -11.88, 7.41]} rotation={[-3.09, 0.28, 1.79]} />
                <group name="R_arm_Pole" position={[-48.27, -15.2, -22.37]} rotation={[-3.1, -0.2, -1.89]} />
                <group name="Null" position={[10.48, 7.21, -31.4]}>
                  <group name="Object_32">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_83" position={[34.2, 1.44, -4.43]} rotation={[-0.06, 0.09, -0.18]} />
                    <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.arms} skeleton={nodes.Object_84.skeleton} />
                  </group>
                </group>
                <group name="armmesh" position={[34.2, 1.44, -4.43]} rotation={[-0.06, 0.09, -0.18]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fps_animated_carbine.glb')
